import{i as c}from"./assets/vendor-32231325.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function l(){return fetch("https://api.thecatapi.com/v1/breeds").then(t=>{if(!t.ok)throw new Error(t.statusText||"Error");return t.json()})}function d(n){const t="https://api.thecatapi.com/v1/images/search",s="live_IPYLEuO65I8syQXtu4lbGRYsVk4VTtkV5G3Csy4a7jLj5CtLAaSsXLN6ZHWBHv37",i=new URLSearchParams({api_key:s,breed_ids:n});return fetch(`${t}?${i}`).then(e=>{if(!e.ok)throw new Error(e.statusText||"Error");return e.json()})}const o={select:document.querySelector(".breed-select"),info:document.querySelector(".cat-info"),loader:document.querySelector(".loader"),error:document.querySelector(".error")};o.select.classList.add("display-none");o.info.classList.add("display-none");o.error.classList.add("display-none");o.select.addEventListener("change",u);l().then(n=>{o.select.innerHTML=n.map(({id:t,name:s})=>`<option value="${t}">${s}</option>`).join(""),o.select.classList.remove("display-none")}).catch(n=>{console.error(n),c.error({message:"Oops! Something went wrong! Try reloading the page!"})}).finally(()=>{o.loader.classList.add("display-none")});function u(n){o.info.innerHTML="",o.loader.classList.remove("display-none"),d(n.target.value).then(t=>{const{url:s,breeds:i}=t[0],{name:e,description:r,temperament:a}=i[0];o.info.classList.remove("display-none"),o.info.innerHTML=`
        <img class="image" src="${s}" alt="${e}" />
        <div class="text-wrapper">
          <h1 class="name">${e}</h1>
          <p class="description">${r}</p>
          <p class="temperament"><b>Temperament:</b> ${a}</p>
        </div>
      `}).catch(t=>{console.error(t),c.error({message:"Oops! Something went wrong! Try reloading the page!"})}).finally(()=>{o.loader.classList.add("display-none")})}
//# sourceMappingURL=commonHelpers.js.map
